name: Deploy Chat server to EC2 with Ansible

on: 
    push:
        branches:
            - master

jobs:
    build-and-push:  
        runs-on: ubuntu-latest # This specifies the job will run on a fresh virtual machine hosted by github
        steps: 
            - name: Checkout code
              # Makes the code available for build, test or deplotyment steps.
              uses: actions/checkout@v3 #To clone the github repo into the runner's workspace.

            - name: Login to Docker
              uses: docker/login-action@v2
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKETHUB_TOKEN }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with: 
                context: ./server
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/secure-chat-server:latest

    deploy: 
        needs: build-and-push
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to EC2
              # This lets us to excecute the remote SSH commands direclty from github actions workflow
              # This is used when Deploying the code to cloud
              # restarting services, running scripts remotely, copying files or trigger build
              uses: appleboy/ssh-action@v1.0.3 
              with: 
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_PRIVATE_KEY }}
                script: |
                    docker stop chat-server || true
                    docker rm chat-server || true
                    docker pull ${{ secrets.DOCKERHUB_USERNAME }}/secure-chat-server:latest
                    docker run -d 8765:8765 --name chat-server ${{ secrets.DOCKERHUB_USERNAME }}/secure-chat-server:latest
                    